name: Build project

on: 
  push:
    tags:
      - '*'  

jobs:
  buildForAllSupportedPlatforms:
    permissions: write-all  
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64
          - StandaloneOSX
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        id: buildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Tag
          buildName: SpaceShooter
      - name: Zip Build
        run: |
          rm -rf build/${{ matrix.targetPlatform }}/Space Shooter_BurstDebugInformation_DoNotShip
          zip -r SpaceShooter-${{ steps.buildStep.outputs.buildVersion }}-${{ matrix.targetPlatform }}.zip build/${{ matrix.targetPlatform }}/*
      - uses: actions/upload-artifact@v3
        with:
          name: SpaceShooter-${{ steps.buildStep.outputs.buildVersion }}-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: SpaceShooter-${{ steps.buildStep.outputs.buildVersion }}-${{ matrix.targetPlatform }}.zip
          tag: ${{ steps.buildStep.outputs.buildVersion }}
          allowUpdates: true
